---
name: Node.js CI

on:
  pull_request:

jobs:
  eslint:
    name: reviewdog / eslint
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
