---
name: yamllint

on:
  pull_request:

jobs:
  eclint:
    name: reviewdog / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: eclint
        uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-pr-review
